### PR TITLE
Ascent now works with multi-room testing

### PR DESCRIPTION
**Pull request by guwahavel**
Stage 9c takes you to Ascent which lets Ascent layouts be loaded with goto

### CODE REVIEW

**Comment by Zamiell** [comment]
is there a particular reason you are doing this degusting hack instead of simply setting the game state flag?

**Comment by guwahavel** [comment]
While this implementation is not perfect in replicating how the rooms would appear in Ascent, it is still an improvement over the current state of Ascent room testing, where multi-room testing is completely impossible. If a better implementation is added later, then that's great, but this is simply a convenience for the time being.

**Comment by Zamiell** [comment]
can you make a PR for proper ascent support using the game state flag? I don't want to merge hacks like this, its super lazy

**Comment by Meowlala** [comment]
stage 9c is actually required to load goto rooms in ascent, you'll notice that if you set the state flag then run "stage 1" goto still leads you to basement rooms rather than ascent basement rooms. This'll be necessary either way for full ascent support.

**Comment by Zamiell** [comment]
ok

**Pull request merged**
