### PR TITLE
"group" sub-tag for entity entries allowing placing an entity in multiple groups / tabs without duplicate entries

### PR DESCRIPTION
**Pull request by Meowlala**
Allows adding additional groups or kinds to entities with a sub tag, like so:
```xml
<entity Group="Random" ID="5" Image="resources/Entities/5.90.0 - RBattery.png" Kind="Pickups" Name="Random Battery" Subtype="0" Variant="90">
	<group Name="Batteries" />
</entity>
```
The group's Name will default to the entity's Group tag if not specified, and the group's Kind will default to the entity's Kind tag similarly.

Duplicate entries for the same entity still work for this purpose, but I've replaced the ones in `EntitiesRepentance.xml` with this system. I haven't gone through the older xml versions to remove duplicate entries yet.

Also forces groups named "Random" to the top of the list via hardcoding to get rid of the " Random" issue; this should probably be changed later to a more flexible system.

### CODE REVIEW

**Comment by Zamiell** [comment]
looks good, lets let @budjmt take a look

**Comment by Zamiell** [comment]
bud took a look and there was a conversation in discord.
dead did you address everything that bud wanted?

**Comment by Meowlala** [comment]
IIRC this PR is fine, most of the suggestions were just about a more flexible future system to handle all of this.

**Comment by Zamiell** [comment]
fantastic, feel free to move on with the second round of entity sorting then

**Pull request merged**
