### PR TITLE
rail maker experiment

### PR DESCRIPTION
**Pull request by SnakeBlock**
made this quickly mostly for personal use so it kinda sucks, but i'll draft pr it

### CODE REVIEW

**Comment by SnakeBlock** [comment]
Maybe I should be more descriptive: this adds a new entry under the Rails section called "Rail Maker", which tiles rails for you. Doesn't support crossroads or pit rails, though.

**Comment by Zamiell** [comment]
@budjmt u wanna take a look?

**Comment by Zamiell** [comment]
snake this has conflicts now after wof's PR, can you clean up the branch?

**Comment by Zamiell** [comment]
i'll close this for now

**Pull request closed without merging**
